name: autoCheck-in
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 22 * * *' # 国际标准时间：北京时间 6:30
    - cron: '25 10 * * *' # 国际标准时间：北京时间 18:25
  workflow_dispatch:

jobs:
  tencentVideoAutoCheck-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # 使用适当的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tencentVideoSign-in-Actions/requirements.txt

      - name: Run check-in-status
        run: |
          cd tencentVideoSign-in-Actions
          python main.py --login_cookie "$LOGIN_COOKIE" --login_url "$LOGIN_URL" --login_url_payload "$LOGIN_URL_PAYLOADLOAD" --PUSHPLUS_TOKEN "$PUSHPLUS_TOKEN" --GET_VIP_INFO_URL_PAYLOAD "$GET_VIP_INFO_URL_PAYLOAD" --IQY_COOKIE "$IQY_COOKIE" --LOG_LEVEL "$LOG_LEVEL" >> run.log
        env:
          LOGIN_COOKIE: ${{ secrets.LOGIN_COOKIE }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          LOGIN_URL_PAYLOADLOAD: ${{ secrets.LOGIN_URL_PAYLOADLOAD }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          GET_VIP_INFO_URL_PAYLOAD: ${{ secrets.GET_VIP_INFO_URL_PAYLOAD }}
          IQY_COOKIE: ${{ secrets.IQY_COOKIE }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}

      - name: Append Success Log
        run: |
          echo "$(date +%Y-%m-%d\ %H:%M:%S) - 今日任务执行成功" >> run.log

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: run.log

      - name: Commit and push log
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
